#!/bin/sh

GWMODE=$(uci get batman-adv.bat0.gw_mode)
LINK=$(ethtool eth0 | awk '/Link detected/ {print $3}')
GREENLED=$(cat /sys/class/leds/ubnt\:green\:dome/brightness)

if [ "$LINK" = "yes" ] && [ "$GWMODE" = "client" ];

then
	echo "
	set network.wan.ifname='eth0'
	set network.lan.ifname='eth1 bat0'
	set network.bat.proto='none'
	set batman-adv.bat0.gw_mode='server'
	commit" \
	| uci batch
	/etc/init.d/network restart
	/etc/init.d/cjdns restart
	sleep 10
	logger -t batman-adv "Gateway mode - server"
fi

if [ "$LINK" = "no" ] && [ "$GWMODE" = "server" ];

then	
	echo "
	set network.wan.ifname='bat0'
	set network.lan.ifname='eth1'
	set network.bat.proto='dhcp'
	set batman-adv.bat0.gw_mode='client'
	commit" \
	| uci batch
	/etc/init.d/network restart
	/etc/init.d/cjdns restart
	sleep 10
	logger -t batman-adv "Gateway mode - client"
fi

if [ "$GWMODE" = "client" ];

then
        echo 0 > /sys/class/leds/ubnt\:green\:dome/brightness
        echo 1 > /sys/class/leds/ubnt\:orange\:dome/brightness
        echo timer > /sys/class/leds/ubnt\:green\:dome/trigger
        echo 100 > /sys/class/leds/ubnt\:green\:dome/delay_on
        echo 10000 > /sys/class/leds/ubnt\:green\:dome/delay_off
else
        echo 0 > /sys/class/leds/ubnt\:orange\:dome/brightness
        echo 0 > /sys/class/leds/ubnt\:green\:dome/brightness
        echo 0 > /sys/class/leds/ubnt\:green\:dome/delay_off
        echo 1 > /sys/class/leds/ubnt\:green\:dome/brightness
fi
