#!/bin/sh

while getopts "o:w:s:e:k:i:s:m:" opt; do
  case $opt in
    o)	OPERATION=${OPTARG};; 
    w)	WIRELESS_ID=${OPTARG};;   
    s)	SSID=${OPTARG};;
    e)	ENCRYPTION=${OPTARG};;
    k) 	ENCRYPTION_KEY=${OPTARG};;
    i)	IF_NAME=${OPTARG};;
    s)	IP_ADDR=${OPTARG};;
    m)	NETMASK=${OPTARG};;
  esac
done

if [ "$OPERATION" = "add" ];
then
	#################################### WIRELESS network configuration
	echo "
	## Create a new wireless interface
	set wireless.$WIRELESS_ID=wifi-iface
	set wireless.$WIRELESS_ID.device='radio0'
	set wireless.$WIRELESS_ID.network=$WIRELESS_ID
	set wireless.$WIRELESS_ID.ifname=$IF_NAME
	set wireless.$WIRELESS_ID.mode='ap'
	set wireless.$WIRELESS_ID.ssid=$SSID
	
	if [ "$ENCRYPTION" = "" ] && [ "$ENCRYPTION_KEY" = "" ];
	then
		set wireless.$WIRELESS_ID.encryption=$ENCRYPTION
		set wireless.$WIRELESS_ID.key=$ENCRYPTION_KEY
	else
		set wireless.$WIRELESS_ID.encryption=none
	fi
	
	set wireless.$WIRELESS_ID.hidden='0'
	commit wireless" \
	| uci batch

	#################################### NETWORK configuration
	echo "
	set network.$WIRELESS_ID=interface
	set network.$WIRELESS_ID.proto='static'
	set network.$WIRELESS_ID.ifname='$IF_NAME'
	set network.$WIRELESS_ID.ipaddr='$IP_ADDR'
	set network.$WIRELESS_ID.netmask='$NETMASK'
	commit network" \
	| uci batch

	#################################### DNSMASQ configuration
	echo "
	dhcp.$WIRELESS_ID=dhcp
	dhcp.$WIRELESS_ID.interface='$WIRELESS_ID'
	dhcp.$WIRELESS_ID.start='10'
	dhcp.$WIRELESS_ID.limit='200'
	dhcp.$WIRELESS_ID.leasetime='1h'
	dhcp.$WIRELESS_ID.dhcpv6='server'
	dhcp.$WIRELESS_ID.ra='server'
	commit batman-adv" \
	| uci batch

	#################################### FIREWALL configuration
	echo "
	## Adding interface to public zone
	add_list firewall.@zone[1].network='$WIRELESS_ID'
	commit firewall" \
	| uci batch

	/etc/init.d/network restart
	/etc/init.d/cjdns reload
	logger -t MILK-AP "Wireless network added - $SSID"	
	
elif [ "$OPERATION" = "remove" ];
then
	echo "Operation - $OPERATION"
fi