#!/bin/sh

if [ "$INTERFACE" = "wan" ] && [ "$ACTION" = "ifup" ];
then
	uci set batman-adv.bat0.gw_mode='server'
	uci commit
	/etc/init.d/dnsmasq enable
	/etc/init.d/dnsmasq start
	echo 0 > /sys/class/leds/ubnt\:orange\:dome/brightness
	echo 0 > /sys/class/leds/ubnt\:green\:dome/brightness
	echo 0 > /sys/class/leds/ubnt\:green\:dome/delay_off
	echo 1 > /sys/class/leds/ubnt\:green\:dome/brightness
	logger -t batman-adv "Gateway mode - server"
	batctl gw server

fi

if [ "$INTERFACE" = "wan" ] && [ "$ACTION" = "ifdown" ];
then
	uci set batman-adv.bat0.gw_mode='client'
	uci commit
	echo 0 > /sys/class/leds/ubnt\:green\:dome/brightness
	echo 0 > /sys/class/leds/ubnt\:orange\:dome/brightness
	echo 1 > /sys/class/leds/ubnt\:orange\:dome/brightness
	echo timer > /sys/class/leds/ubnt\:green\:dome/trigger
	echo 100 > /sys/class/leds/ubnt\:green\:dome/delay_on
	echo 10000 > /sys/class/leds/ubnt\:green\:dome/delay_off
	logger -t batman-adv "Gateway mode - client"
	/etc/init.d/dnsmasq stop
	/etc/init.d/dnsmasq disable
	batctl gw client
fi